// Copyright (c) 2024 by Christopher Antos
// License: http://opensource.org/licenses/MIT

// vim: set et ts=8 sw=4 cino={0s:

#include "pch.h"
#include "usage.h"

const char c_usage[] = "%s -? for help.";

const char c_long_usage[] =
"Displays a list of file and subdirectories in a directory.\n"
"\n"
"%s [options] [drive:][path][filename]\n"
"\n"
"  [drive:][path][filename]\n"
"		Specifies drive, directory, and/or files to list.  Prefix the\n"
"		filename part with :: to use a regular expression.  For more\n"
"		information about regular expressions use '-? regex'.\n"
"\n"
"  -?		Display this help text.\n"
"  -? colors	Display help text on color coding the file list.\n"
"  -? pictures	Display help text on format pictures.\n"
"  -? regex	Display help text on regular expression syntax.\n"
"  -V		Display version information.\n"
"\n"
"  -,		Display the thousand separator in sizes.  This is the default.\n"
"  -1		Uses one column list format.\n"
"  -2		Uses two column list format (or more on wide consoles).\n"
"  -4		Uses four column list format (or more on wide consoles).\n"
"  -a		Display all files (include hidden and system files).  By\n"
"		default system and hidden files are not displayed.\n"
"  -a[...]	Display files with the specified attributes.  If attributes\n"
"		are combined, all attributes must match (-arhs only lists\n"
"		files with all three attributes set).  Using the - prefix\n"
"		excludes files with that attribute (-arh-s lists files that\n"
"		are read-only and hidden and not system).  Using the + prefix\n"
"		includes files that have any of the + attributes set (-ar+h+s\n"
"		lists files that are read-only and have the hidden or system\n"
"		attributes set).\n"
"		  r  Read-only files			e  Encrypted files\n"
"		  h  Hidden files			t  Temporary files\n"
"		  s  System files			p  Sparse files\n"
"		  a  Files ready for archiving		c  Compressed files\n"
"		  d  Directories			o  Offline files\n"
"		  i  Not content indexed files\n"
"		  j  Reparse points (mnemonic for junction)\n"
"		  l  Reparse points (mnemonic for link)\n"
"		  +  Prefix meaning any\n"
"		  -  Prefix meaning not\n"
"  -b		Uses bare format (only filenames, no header/detail/summary).\n"
"  -c		Display compression ratio.\n"
"  -E[...]	Override the truncation character for file names that don't\n"
"		fit in the allotted space.  Specify a Unicode character value\n"
"		in hexadecimal (e.g. -E2192 is a right-pointing arrow and\n"
"		-E25b8 is a right-pointing triangle).\n"
"  -f[...]	Use the specified format picture to list files.  For more\n"
"		information about format pictures use '-? pictures'.\n"
"  -F		Display full file paths in the file name column.\n"
"  -h		Hide . and .. directories.\n"
"  -j		Justify file names in FAT list format.\n"
"  -J		Justify file names in non-FAT list formats.\n"
"  -l		Display file names using lower case.\n"
"  -L		Display dates and times in current locale format (like CMD\n"
"		with extensions enabled).\n"
"  -M		Include time in wide list format.\n"
"  -n		Use normal list format (even for FAT volumes).  This is the\n"
"		default for non-FAT volumes.\n"
"  -n-		Reset disabled options (below).\n"
"  -n[...]	Disable options:\n"
"		  v  Suppress the volume information\n"
"		  h  Suppress the header\n"
"		  d  Skip hidden directories (when used with -s)\n"
"		  j  Skip junctions (when used with -s)\n"
"		  s  Suppress the summary\n"
"		  r  Skip files with no alternate data streams\n"
"		  c  Disable color coding (use '-? colors' for more info)\n"
"		  w  Disable word sort (uses string sort instead)\n"
"		  -  Prefix to disable option (this is the default)\n"
"		  +  Prefix to enable option\n"
"  -o[...]	List files in sorted order by the specified options:\n"
"		  n  Name [and extension if 'e' not specified] (alphabetic)\n"
"		  e  Extension (alphabetic)\n"
"		  g  Group directories first\n"
"		  d  Date/time (oldest first)\n"
"		  s  Size (smallest first)\n"
"		  c  Compression ratio\n"
"		  a  Simple ASCII order (sort \"10\" before \"2\")\n"
"		  u  Unsorted\n"
"		  r  Reverse order for all options\n"
"		  -  Prefix to reverse order\n"
"  -p		Pause after each screen full of information.\n"
"  -q		Display the owner of the file.\n"
"  -r		Display alternate data streams of the file.\n"
"  -s		Displays files in specified directory and all subdirectories.\n"
"  -S		Don't abbreviate file size in 1 column FAT list format\n"
"		(implied by -S[acf]).\n"
"  -S[acf]	Controls which size field is displayed or used for sorting:\n"
"		  a  Allocation size\n"
"		  c  Compressed size\n"
"		  f  File size (default)\n"
"  -t		Display file attributes.\n"
"  -T		Don't abbreviate time (implied by -T[acw]).\n"
"  -T[acw]	Controls which time field is displayed or used for sorting:\n"
"		  a  Access time\n"
"		  c  Creation time\n"
"		  w  Write time (default)\n"
"  -u		Display directory size usage data.\n"
"  -v		Sort columns vertically (default is horizontally).\n"
"  -w		Use wide list format.\n"
"  -x		Display 8.3 short file names.\n"
"  -Y		Include abbreviated time when showing more than 1 column.\n"
"  -z		Use FAT list format (filenames on left, etc).  This is the\n"
"		default for FAT volumes.\n"
"  -Z		Include abbreviated file size when showing more than 1 column.\n"
"\n"
"Options may be preset in the FSCMD environment variable.  Override preset\n"
"options by following any option with - (hyphen), for example -h-.\n"
"\n"
"Specify color coding rules in the FSCOLORDIR environment variable, or set it\n"
"to * to use some predefined rules.  Use '-? colors' for more info.\n"
;

const char c_help_colors[] =
// TODO: Rewrite help after rewriting implementation.
"Set the FSCOLORDIR environment variable to control how files and directories\n"
"are colored.  The format is:\n"
"\n"
"  condition: color; condition: color; ...\n"
"\n"
"Any number of conditions can be given; use semicolons to separate them and\n"
"build a list of many coloring rules.  The first matching condition is used.\n"
"\n"
"Conditions are a combination of attributes or file extensions.  If any \n"
"attribute or file extension matches, then the condition is true.  Combine\n"
"attributes and file extensions using the .and., .or., .xor., and .not.\n"
"operators to create more complex rules (operators are evaluated from left to\n"
"right, parentheses are not supported, and Boolean short circuiting applies).\n"
"\n"
"Attributes can be any of the following (synonyms in brackets):\n"
"  archive			notindexed\n"
"  compressed			offline\n"
"  directory [dirs]		readonly [rdonly]\n"
"  encrypted			sparse\n"
"  hidden			system\n"
"  junction			temporary\n"
"  normal (files with no attributes set)\n"
"\n"
"File extensions can include ? and * wildcards, and can also include character\n"
"sets enclosed in [], for example \"ab[xyz]\" matches abx, aby, and abz.  Sets\n"
"can include ranges, for example \"[a-z]\" matches any letter.  If the first\n"
"character in the set is ! the set excludes the listed characters, for example\n"
"\"[!0-9]\" matches anything except digits.  The ? character in a set matches any\n"
"character, but only if there's a character to match:  for example \"ab[?]\" will\n"
"match abc, but will not match ab.\n"
"\n"
"Colors are 'foregroundcolor' or 'foregroundcolor on backgroundcolor'.\n"
"The color names are black, blue, green, cyan, red, magenta, yellow, and\n"
"white, and can be prefixed with bright (all colors can be abbreviated as\n"
"their first three letters).  If the background color is omitted, then only\n"
"the foreground color is applied.  This can be useful if you use command\n"
"windows with different background colors; the background color is inherited\n"
"from the console window.\n"
"\n"
"Examples:\n"
"\n"
"  system hidden:bright red on black\n"
"		Colors files with the system or hidden attributes as bright\n"
"		red on black.\n"
"\n"
"  directory:bri yel on bla; tmp temporary:cya on bla\n"
"		Colors files with the directory attribute as bright yellow on\n"
"		black, and files with the temporary attribute or tmp file\n"
"		extension as cyan on black.\n"
"\n"
"  exe bat cmd com pl vbs:bri gre\n"
"		Colors files with the exe, bat, cmd, com, pl, or vbs file\n"
"		extensions as bright green.\n"
"\n"
"Or set FSCOLORDIR to * to use the following set of predefined color rules:\n"
"\n"
"  hidden system:bri red on bla; \n"
"  directory:bri yel on bla; \n"
"  readonly .and. exe com bat btm cmd pif pl lnk vbs:bri gre on bla; \n"
"  exe com bat btm cmd pif pl lnk vbs:bri whi on bla; \n"
"  dpk:bri cya on bla; \n"
"  zip:cya on bla; \n"
"  arc arj lzh rar zoo:mag on bla; \n"
"  readonly:gre on bla\n"
"\n"
"TakeCommand/4NT compatibility:  If the FSCOLORDIR environment variable is not\n"
"set then COLORDIR is checked.  If COLORDIR is also not set but 4DOS is set to\n"
"point at a directory, then COLORDIR is read from a tcmd.ini or 4nt.ini file\n"
"in that directory.  Regular expressions are not yet supported in the coloring\n"
"rules.  Visit http://www.jpsoft.com for info on TakeCommand/4NT.\n"
;

const char c_help_pictures[] =
"Use the -f option to specify a custom format picture to list files.  Format\n"
"picture field types and styles are case sensitive:  field types are uppercase\n"
"and field styles are lowercase.\n"
"\n"
"Examples:\n"
"  \"F  Sm\"		Filename  3.2M\n"
"  \"Ds  Sm Trh F18\"	10/04/09  13:45  123K r_ SomeVeryLongFilen%c\n"
"\n"
"Format picture field types:\n"
"  F[#flx]	Filename field.  By default this automatically chooses the\n"
"		field width and style based on the other options used.\n"
"		  #	A number indicating the width for the field.  If a\n"
"			file name is wider, it is truncated.  If a file name\n"
"			is narrower, it is padded with spaces to the right.\n"
"		  f	Use FAT name format.\n"
"		  l	Show the long file name.\n"
"		  x	Show the short file name.\n"
"  S[msacf]	Size field.  By default this automatically chooses the field\n"
"		width and style based on the other options used.\n"
"		  m	Use mini format (use 4 characters, always abbreviate).\n"
"		  s	Use short format (use 9 characters, abbreviate when\n"
"			necessary).\n"
"		  a	Show the file allocation size.\n"
"		  c	Show the compressed file size.\n"
"		  f	Show the file data size.\n"
"  D[lmsxacw]	Date and time field.  By default this automatically chooses the\n"
"		field width and style based on the other options used.\n"
"		  l	Use locale format (like CMD with extensions enabled).\n"
"		  m	Use mini format (11 characters with time for recent\n"
"			files or year for older files).\n"
"		  n	Use normal format (17 characters with four digit year).\n"
"		  s	Use short format (15 characters with two digit year).\n"
"		  x	Use extended format (24 characters with four digit\n"
"			year, minutes, and milliseconds).\n"
"		  a	Show the last access time.\n"
"		  c	Show the creation time.\n"
"		  w	Show the last write time.\n"
"  C[?]		Compression ratio field.  By default this shows the field even\n"
"		if the corresponding option was not specified.\n"
"		  ?	Show only if the corresponding option was specified.\n"
"  O[?]		Owner field.  By default this shows the field even if the\n"
"		corresponding option was not specified.\n"
"		  ?	Show only if the corresponding option was specified.\n"
"  X[?]		Short name field.  By default this shows the field even if the\n"
"		corresponding option was not specified.\n"
"		  ?	Show only if the corresponding option was specified.\n"
"  T[...]	Attributes field.  By default this shows the field even if the\n"
"		corresponding option was not specified, and shows all file\n"
"		attributes.  Control which attributes are listed as follows:\n"
"		  ?	Show only if the corresponding option was specified.\n"
"		  r	Read-only			  e	Encrypted\n"
"		  h	Hidden				  t	Temporary\n"
"		  s	System				  p	Sparse\n"
"		  a	Ready for archiving		  c	Compressed\n"
"		  d	Directory			  o	Offline\n"
"		  i	Not content indexed\n"
"		  j	Reparse point (mnemonic for junction)\n"
"		  l	Reparse point (mnemonic for link)\n"
"\n"
"Other characters in the format picture are output as-is.  To ensure a\n"
"character is output as-is rather than being treated as a field type (etc),\n"
"use \\ to escape the character (e.g. \"\\F:F\" shows \"F:MyFile.doc\").\n"
"\n"
"For some field types ? suppresses the field if the corresponding option was\n"
"not specified.  When a field is suppressed, normally the field and the spaces\n"
"immediately preceding it are omitted from the resulting format picture.  For\n"
"finer control over what part of the format picture is omitted, surround the\n"
"text to be omitted using the [ and ] characters.  Everything between the\n"
"brackets will be shown or omitted as a unit, and the brackets themselves are\n"
"not shown (e.g. \"F [(C?) ]Sm\" shows \"File (12%) 1.2M\" or \"File 1.2M\").\n"
"\n"
"The -F option fits the full path name into the filename field, if the field is\n"
"at the end of the format picture.\n"
"\n"
"The -w option fits as many files as possible onto each line, using the custom\n"
"format picture.  The -2 option is incompatible with format pictures.\n"
"\n"
"The -r option forces a single column list, but fits the stream name into the\n"
"filename field(s).  If the filename field is at the end of the format picture\n"
"then the entire stream names are shown; otherwise the stream names are\n"
"truncated to the width of the longest file name.\n"
;

static const char c_help_regex[] =
"Regular expressions specify a substring to find.  In addition, several special\n"
"operators perform advanced searches.\n"
"\n"
"To use a regular expression as a filename pattern, use :: followed by the\n"
"regular expression.  When specifying both a path and a regular expression, the\n"
":: must precede the regular expression, for example \"folder\\::regex\".  If the\n"
"regular expression contains spaces or characters with special meaning to the\n"
"shell (such as |, <, >) then enclose the expression in double quotes.\n"
"\n"
"Note that regular expressions are not natively supported by the OS, so all\n"
"filenames must be retrieved and compared with the regular expression.  This can\n"
"make using regular expressions much slower than using ? and * wildcards.\n"
"\n"
// TODO: Describe basics of ECMAScript regex and provide link to full docs.
"  Operator	Description\n"
"  ^		Matches the null string at the beginning of a line.\n"
"  $		Matches the null string at the end of a line.\n"
"  .		Matches any character.\n"
"  [set]		Matches any characters in the set.  The - character selects a\n"
"		range of characters.  The expression [a-z] matches any\n"
"		lowercase letter from a to z.  To select the ] character, put\n"
"		it at the beginning of the set.  To select the - character, put\n"
"		it at the end of the set.  To select the ^ character, put it\n"
"		anywhere except immediately after the opening bracket (which\n"
"		selects the complement of the set; see below).\n"
"  [^set]	Matches any characters not in the set (matches the complement\n"
"		of the set).  The syntax for a complement set is the same as\n"
"		the syntax for a normal set (above), except that it is preceded\n"
"		by a ^ character.\n"
"  (abc)		Matches abc, and tags it as a sub-expression for retrieval.\n"
"  abc|def	Matches abc or def.\n"
"  x?		Matches 0 or 1 occurrences of the character x (or set, or\n"
"		tagged sub-expression).\n"
"  x+		Matches 1 or more occurrences of the character x (or set, or\n"
"		tagged sub-expression).\n"
"  x*		Matches 0 or more occurrences of the character x (or set, or\n"
"		tagged sub-expression).\n"
"  \\<		Matches the null string at the beginning of a word.\n"
"  \\>		Matches the null string at the end of a word.\n"
"  \\x		Literally matches the special character x.  Special characters\n"
"		are ^, $, ., [, (, ), |, ?, +, *, and \\.\n"
;

